#include "MixedFilamentExportDialog.hpp"

#include "GUI_App.hpp"
#include "I18N.hpp"
#include "MixedColorMatchHelpers.hpp"
#include "MsgDialog.hpp"

#include "libslic3r/Config.hpp"
#include "libslic3r/MixedFilamentExport.hpp"
#include "libslic3r/PresetBundle.hpp"

#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/checklst.h>
#include <wx/filedlg.h>
#include <wx/filename.h>
#include <wx/radiobut.h>
#include <wx/scrolwin.h>
#include <wx/sizer.h>
#include <wx/statbox.h>
#include <wx/stattext.h>
#include <wx/stdpaths.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <exception>

namespace Slic3r { namespace GUI {

namespace {

constexpr std::uint64_t max_xlsx_data_rows = 1'048'575;

std::uint64_t combination_count(size_t n, size_t k)
{
    if (n < k)
        return 0;

    k                    = std::min(k, n - k);
    std::uint64_t result = 1;
    for (size_t i = 1; i <= k; ++i)
        result = result * static_cast<std::uint64_t>(n - k + i) / static_cast<std::uint64_t>(i);
    return result;
}

wxString from_utf8(const std::string& value) { return wxString::FromUTF8(value.c_str()); }

std::string to_utf8(const wxString& value) { return value.ToUTF8().data(); }

} // namespace

MixedFilamentExportDialog::MixedFilamentExportDialog(wxWindow* parent)
    : DPIDialog(parent,
                wxID_ANY,
                _L("Export mixed filament catalog"),
                wxDefaultPosition,
                wxDefaultSize,
                wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER)
{
    load_physical_filaments();

    auto* dialog_sizer      = new wxBoxSizer(wxVERTICAL);
    m_scrolled_content      = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxVSCROLL);
    auto*     main_sizer    = new wxBoxSizer(wxVERTICAL);
    const int scroll_pixels = FromDIP(12);
    m_scrolled_content->SetScrollRate(0, scroll_pixels);

    auto* introduction = new wxStaticText(
        m_scrolled_content, wxID_ANY,
        _L("Export the mixed filaments already generated by the slicer, or build a ratio catalog from the physical filaments below."));
    introduction->Wrap(FromDIP(520));
    main_sizer->Add(introduction, 0, wxEXPAND | wxLEFT | wxRIGHT | wxTOP, FromDIP(16));

    auto* physical_box = new wxStaticBoxSizer(wxVERTICAL, m_scrolled_content, _L("Current physical filaments"));
    m_filament_list    = new wxCheckListBox(physical_box->GetStaticBox(), wxID_ANY, wxDefaultPosition, FromDIP(wxSize(-1, 170)));
    for (const PhysicalFilament& filament : m_physical_filaments) {
        wxString label = wxString::Format(_L("Slot %u    %s    %s"), filament.slot, from_utf8(filament.name).c_str(),
                                          from_utf8(filament.color_hex).c_str());
        if (filament.td_mm.has_value())
            label += wxString::Format(_L("    TD %.2f mm"), *filament.td_mm);
        else
            label += "    " + _L("TD not set");
        const unsigned int row = m_filament_list->Append(label);
        m_filament_list->Check(row, true);
    }
    if (m_physical_filaments.empty()) {
        m_filament_list->Append(_L("No physical filament slots are loaded."));
        m_filament_list->Enable(false);
    }
    physical_box->Add(m_filament_list, 1, wxEXPAND | wxALL, FromDIP(8));
    main_sizer->Add(physical_box, 1, wxEXPAND | wxLEFT | wxRIGHT | wxTOP, FromDIP(16));

    auto* mode_box   = new wxStaticBoxSizer(wxVERTICAL, m_scrolled_content, _L("Export contents"));
    m_export_current = new wxRadioButton(mode_box->GetStaticBox(), wxID_ANY, _L("Export current enabled mixed filaments directly"),
                                         wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    m_export_current->SetValue(true);
    mode_box->Add(m_export_current, 0, wxEXPAND | wxLEFT | wxRIGHT | wxTOP, FromDIP(8));

    auto* direct_help = new wxStaticText(mode_box->GetStaticBox(), wxID_ANY,
                                         _L("Uses the enabled mixed-filament definitions and their current slicer ratios."));
    direct_help->Wrap(FromDIP(520));
    mode_box->Add(direct_help, 0, wxEXPAND | wxLEFT | wxRIGHT | wxBOTTOM, FromDIP(8));

    m_generate_automatic = new wxRadioButton(mode_box->GetStaticBox(), wxID_ANY, _L("Generate automatic ratio catalog"));
    mode_box->Add(m_generate_automatic, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(8));

    auto* automatic_options = new wxBoxSizer(wxVERTICAL);
    m_include_pairs         = new wxCheckBox(mode_box->GetStaticBox(), wxID_ANY, _L("2-filament combinations (9 ratios)"));
    m_include_triples       = new wxCheckBox(mode_box->GetStaticBox(), wxID_ANY, _L("3-filament combinations (10 ratios)"));
    m_include_quads         = new wxCheckBox(mode_box->GetStaticBox(), wxID_ANY, _L("4-filament combinations (79 ratios)"));
    m_include_pairs->SetValue(true);
    m_include_triples->SetValue(true);
    m_include_quads->SetValue(true);
    automatic_options->Add(m_include_pairs, 0, wxBOTTOM, FromDIP(4));
    automatic_options->Add(m_include_triples, 0, wxBOTTOM, FromDIP(4));
    automatic_options->Add(m_include_quads, 0);
    mode_box->Add(automatic_options, 0, wxEXPAND | wxLEFT | wxRIGHT | wxTOP | wxBOTTOM, FromDIP(12));
    main_sizer->Add(mode_box, 0, wxEXPAND | wxLEFT | wxRIGHT | wxTOP, FromDIP(16));

    m_include_kmks = new wxCheckBox(m_scrolled_content, wxID_ANY, _L("Add KM/K-S predicted colors"));
    m_include_kmks->SetToolTip(_L("Adds a second predicted-color column generated by the KM/K-S color engine."));
    main_sizer->Add(m_include_kmks, 0, wxEXPAND | wxLEFT | wxRIGHT | wxTOP, FromDIP(20));

    m_count_summary     = new wxStaticText(m_scrolled_content, wxID_ANY, wxEmptyString);
    wxFont summary_font = m_count_summary->GetFont();
    summary_font.SetWeight(wxFONTWEIGHT_BOLD);
    m_count_summary->SetFont(summary_font);
    main_sizer->Add(m_count_summary, 0, wxEXPAND | wxLEFT | wxRIGHT | wxTOP | wxBOTTOM, FromDIP(16));

    auto* button_sizer = new wxBoxSizer(wxHORIZONTAL);
    button_sizer->AddStretchSpacer();
    m_export_button     = new wxButton(this, wxID_OK, _L("Export XLSX"));
    auto* cancel_button = new wxButton(this, wxID_CANCEL, _L("Cancel"));
    button_sizer->Add(m_export_button, 0, wxRIGHT, FromDIP(8));
    button_sizer->Add(cancel_button, 0);

    m_scrolled_content->SetSizer(main_sizer);
    dialog_sizer->Add(m_scrolled_content, 1, wxEXPAND);
    dialog_sizer->Add(button_sizer, 0, wxEXPAND | wxALL, FromDIP(16));
    SetSizer(dialog_sizer);
    SetMinSize(FromDIP(wxSize(560, 420)));
    SetSize(FromDIP(wxSize(760, 700)));
    m_scrolled_content->FitInside();
    Layout();
    CentreOnParent();

    m_export_current->Bind(wxEVT_RADIOBUTTON, [this](wxCommandEvent&) { update_state_and_summary(); });
    m_generate_automatic->Bind(wxEVT_RADIOBUTTON, [this](wxCommandEvent&) { update_state_and_summary(); });
    m_include_pairs->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent&) { update_state_and_summary(); });
    m_include_triples->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent&) { update_state_and_summary(); });
    m_include_quads->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent&) { update_state_and_summary(); });
    m_filament_list->Bind(wxEVT_CHECKLISTBOX, [this](wxCommandEvent&) { update_state_and_summary(); });
    m_export_button->Bind(wxEVT_BUTTON, &MixedFilamentExportDialog::on_export, this);

    update_state_and_summary();
    wxGetApp().UpdateDlgDarkUI(this);
}

void MixedFilamentExportDialog::load_physical_filaments()
{
    m_physical_filaments.clear();

    const PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    if (preset_bundle == nullptr)
        return;

    const DynamicPrintConfig&  project_config = preset_bundle->project_config;
    const ConfigOptionStrings* color_opt      = project_config.option<ConfigOptionStrings>("filament_colour");

    const size_t filament_count = static_cast<size_t>(std::max(wxGetApp().filaments_cnt(), 0));
    m_physical_filaments.reserve(filament_count);
    std::vector<std::string> physical_colors;
    physical_colors.reserve(filament_count);
    for (size_t i = 0; i < filament_count; ++i) {
        PhysicalFilament filament;
        filament.slot      = static_cast<unsigned int>(i + 1);
        filament.name      = i < preset_bundle->filament_presets.size() && !preset_bundle->filament_presets[i].empty() ?
                                 preset_bundle->filament_presets[i] :
                                 to_utf8(wxString::Format(_L("Filament %llu"), static_cast<unsigned long long>(i + 1)));
        filament.color_hex = color_opt != nullptr && i < color_opt->values.size() && !color_opt->values[i].empty() ? color_opt->values[i] :
                                                                                                                     "#26A69A";
        physical_colors.emplace_back(filament.color_hex);
        m_physical_filaments.emplace_back(std::move(filament));
    }

    const MixedFilamentDisplayContext display_context = build_mixed_filament_display_context(physical_colors);
    for (size_t i = 0; i < m_physical_filaments.size() && i < display_context.physical_tds.size(); ++i) {
        const double td_mm = display_context.physical_tds[i];
        if (std::isfinite(td_mm) && td_mm > 0.0)
            m_physical_filaments[i].td_mm = td_mm;
    }
}

std::vector<MixedFilamentExportDialog::PhysicalFilament> MixedFilamentExportDialog::selected_physical_filaments() const
{
    std::vector<PhysicalFilament> selected;
    selected.reserve(m_physical_filaments.size());
    for (size_t i = 0; i < m_physical_filaments.size(); ++i) {
        if (m_filament_list->IsChecked(static_cast<unsigned int>(i)))
            selected.emplace_back(m_physical_filaments[i]);
    }
    return selected;
}

void MixedFilamentExportDialog::update_state_and_summary()
{
    const bool automatic = m_generate_automatic->GetValue();
    if (!m_physical_filaments.empty())
        m_filament_list->Enable(automatic);
    m_include_pairs->Enable(automatic);
    m_include_triples->Enable(automatic);
    m_include_quads->Enable(automatic);

    bool can_export = false;
    if (automatic) {
        const size_t        selected_count = selected_physical_filaments().size();
        const std::uint64_t pair_sets      = m_include_pairs->GetValue() ? combination_count(selected_count, 2) : 0;
        const std::uint64_t triple_sets    = m_include_triples->GetValue() ? combination_count(selected_count, 3) : 0;
        const std::uint64_t quad_sets      = m_include_quads->GetValue() ? combination_count(selected_count, 4) : 0;
        const std::uint64_t unique_sets    = pair_sets + triple_sets + quad_sets;
        const std::uint64_t row_count      = pair_sets * 9 + triple_sets * 10 + quad_sets * 79;
        const std::uint64_t component_rows = pair_sets * 9 * 2 + triple_sets * 10 * 3 + quad_sets * 79 * 4;

        if (row_count > max_xlsx_data_rows || component_rows > max_xlsx_data_rows) {
            wxString summary = wxString::Format(_L("%llu unique filament sets would produce %llu recipe rows and %llu component rows."),
                                                static_cast<unsigned long long>(unique_sets), static_cast<unsigned long long>(row_count),
                                                static_cast<unsigned long long>(component_rows));
            summary += " " + _L("This exceeds Excel's worksheet limit. Reduce the selected filaments or combination families.");
            m_count_summary->SetLabel(summary);
        } else {
            m_count_summary->SetLabel(
                wxString::Format(_L("%llu unique filament sets will produce %llu spreadsheet rows (%llu physical filaments selected)."),
                                 static_cast<unsigned long long>(unique_sets), static_cast<unsigned long long>(row_count),
                                 static_cast<unsigned long long>(selected_count)));
            can_export = row_count > 0;
        }
    } else {
        const PresetBundle* preset_bundle = wxGetApp().preset_bundle;
        const size_t        enabled_count = preset_bundle != nullptr ? preset_bundle->mixed_filaments.enabled_count() : 0;
        m_count_summary->SetLabel(
            wxString::Format(_L("%llu enabled mixed filament rows will be exported."), static_cast<unsigned long long>(enabled_count)));
        can_export = enabled_count > 0;
    }

    m_count_summary->Wrap(FromDIP(520));
    m_export_button->Enable(can_export);
    m_scrolled_content->FitInside();
    Layout();
}

void MixedFilamentExportDialog::on_export(wxCommandEvent&)
{
    const PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    if (preset_bundle == nullptr) {
        MessageDialog(this, _L("The current filament configuration is unavailable."), _L("Export mixed filament catalog"),
                      wxOK | wxICON_WARNING)
            .ShowModal();
        return;
    }

    wxString default_dir = wxStandardPaths::Get().GetUserDir(wxStandardPaths::Dir_Documents);
    if (default_dir.empty())
        default_dir = wxGetHomeDir();
    wxFileDialog file_dialog(this, _L("Export mixed filament catalog"), default_dir, "mixed-filament-catalog.xlsx",
                             _L("Excel workbooks (*.xlsx)|*.xlsx"), wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
    if (file_dialog.ShowModal() != wxID_OK)
        return;

    wxFileName output_path(file_dialog.GetPath());
    if (output_path.GetExt().empty())
        output_path.SetExt("xlsx");
    else if (!output_path.GetExt().IsSameAs("xlsx", false)) {
        MessageDialog(this, _L("The export file name must end with .xlsx."), _L("Export mixed filament catalog"), wxOK | wxICON_WARNING)
            .ShowModal();
        return;
    }

    std::vector<MixedFilamentExportPhysicalFilament> physical_filaments;
    std::vector<std::string>                         physical_colors;
    physical_filaments.reserve(m_physical_filaments.size());
    physical_colors.reserve(m_physical_filaments.size());
    for (size_t i = 0; i < m_physical_filaments.size(); ++i) {
        const PhysicalFilament&             source = m_physical_filaments[i];
        MixedFilamentExportPhysicalFilament filament;
        filament.id        = source.slot;
        filament.name      = source.name;
        filament.color_hex = source.color_hex;
        filament.td_mm     = source.td_mm;
        filament.selected  = m_filament_list->IsChecked(static_cast<unsigned int>(i));
        physical_filaments.emplace_back(std::move(filament));
        physical_colors.emplace_back(source.color_hex);
    }

    try {
        std::vector<MixedFilamentExportRecipe> recipes;
        MixedFilamentExportPredictionOptions   prediction;
        prediction.include_km_ks = m_include_kmks->GetValue();
        prediction.use_td        = MixedFilamentManager::use_td_for_color_prediction();

        if (m_generate_automatic->GetValue()) {
            MixedFilamentAutomaticExportOptions options;
            options.include_two_filament   = m_include_pairs->GetValue();
            options.include_three_filament = m_include_triples->GetValue();
            options.include_four_filament  = m_include_quads->GetValue();
            options.prediction             = prediction;
            recipes                        = make_automatic_mixed_filament_export_recipes(physical_filaments, options);
        } else {
            const MixedFilamentDisplayContext display_context = build_mixed_filament_display_context(physical_colors);
            recipes = make_current_mixed_filament_export_recipes(physical_filaments, preset_bundle->mixed_filaments.mixed_filaments(),
                                                                 display_context, prediction);
        }

        if (recipes.empty()) {
            MessageDialog(this, _L("No mixed filament rows match the selected export options."), _L("Export mixed filament catalog"),
                          wxOK | wxICON_WARNING)
                .ShowModal();
            return;
        }

        const MixedFilamentXlsxWriteResult result = write_mixed_filament_xlsx(to_utf8(output_path.GetFullPath()), physical_filaments,
                                                                              recipes);
        if (!result.success) {
            const wxString error = result.error.empty() ? _L("The XLSX workbook could not be written.") : from_utf8(result.error);
            MessageDialog(this, error, _L("Export mixed filament catalog"), wxOK | wxICON_ERROR).ShowModal();
            return;
        }

        MessageDialog(this,
                      wxString::Format(_L("Exported %llu mixed filament rows to:\n%s"), static_cast<unsigned long long>(recipes.size()),
                                       output_path.GetFullPath().c_str()),
                      _L("Export mixed filament catalog"), wxOK | wxICON_INFORMATION)
            .ShowModal();
        EndModal(wxID_OK);
    } catch (const std::exception& exception) {
        MessageDialog(this,
                      wxString::Format(_L("The mixed filament catalog could not be exported:\n%s"), from_utf8(exception.what()).c_str()),
                      _L("Export mixed filament catalog"), wxOK | wxICON_ERROR)
            .ShowModal();
    }
}

void MixedFilamentExportDialog::on_dpi_changed(const wxRect& suggested_rect)
{
    SetMinSize(FromDIP(wxSize(560, 420)));
    if (!suggested_rect.IsEmpty())
        SetSize(suggested_rect);
    m_scrolled_content->SetScrollRate(0, FromDIP(12));
    m_scrolled_content->FitInside();
    Layout();
    Refresh();
}

}} // namespace Slic3r::GUI
